services:
    dropbot:
        container_name: dropbot-test
        env_file:
          - .env
        build:
          context: .
          dockerfile: ./Dockerfile
        tty: true
        restart: unless-stopped
        volumes:
          - ./downloads:/downloads
        depends_on:
          - bgutil-provider

    bgutil-provider:
        image: brainicism/bgutil-ytdlp-pot-provider:latest
        container_name: bgutil-provider
        expose:
          - "4416"
        restart: unless-stopped
